### ISSUE TITLE
Snes9x 1.60 retroarch nvidia shield

### ISSUE THREAD

**Issue by tuesday96** [snes9xgit/snes9x#537]
After updating core, my roms are unplayable with threaded video  off. I can hear the game but the screen is twisted only visible at the edge's of  the display.

The older snes9x 2010 doesn't suffer from this.

**Comment by Tatsuya79** [comment]
https://github.com/libretro/snes9x/issues/212

What happened recently? Blargg filter? Cropping changes?

**Comment by bearoso** [comment]
This is a sign that the unpacking for the texture upload is wrong. The core end doesn't control that. The best way to figure out what's wrong is to bisect, but I doubt tuesday96 knows how. We'd need someone with the hardware and the means to compile.

@tuesday96, is this the original handheld or a shield tv?

**Comment by funbars** [comment]
Others' script
```
image: Visual Studio 2017

shallow_clone: true

environment:
  ANDROID_NDK: 'C:\ProgramData\Microsoft\AndroidNDK64\android-ndk-r17'

init:
  - set Path=%ANDROID_NDK%;%Path%

build_script:
  - cd jni && ndk-build

artifacts:
  - path: '**\libs\**\*.so'
```

https://github.com/snes9xgit/snes9x/commit/a2ef6e38181d4c345afe4e3e9a51a83f21fe5f30
https://ci.appveyor.com/project/funbars/snes9x/builds/24474604/artifacts

https://github.com/snes9xgit/snes9x/commit/d975010369d39ef7e59af358cdf7ea149520c43a
https://ci.appveyor.com/project/funbars/snes9x/builds/24474606/artifacts
